app = "simulador-btc"

[build]
  image = "node:22-bullseye"

[env]
  MONGODB_URI = "mongodb+srv://renisson:renisson@cluster0.oax4gnk.mongodb.net/simulador?retryWrites=true&w=majority"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true
